name: CI
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - develop
      - master

jobs:
  type-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: run headless tests
        uses: ledgerhq/actions/run-headless@v1.2.0
      - name: upload diffs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v1
        with:
          name: "diff_output"
          path: tests/specs/__image_snapshots__/__diff_output__
