name: generate jest screenshots
on:
  push:
    branches:
      - develop

jobs:
  generate-screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: check if PR is not screenshots already
        uses: ledgerhq/actions/check-pr-screenshots@v1.2.0
      - name: generate new screenshots
        uses: ledgerhq/actions/run-headless@v1.2.0
        with:
          should-update-screenshots: 1
      - name: check diff
        run: git status
        if: ${{ always() }}
      - name: create pull request with new screenshots if needed
        uses: peter-evans/create-pull-request@v2
        with:
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: "[Screenshots] new screenshots for ${{ github.sha }}"
          body: |
            Auto generated screenshots for ${{ github.sha }} by ${{ github.actor }}
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          branch: new-screenshots-${{ github.sha }}
